source_lang: src
target_lang: tgt
task: translation_w_mono
parallel_ratio: 1
mono_ratio: 1
arch: transformer_big_t2t_12e12d
share_all_embeddings: true
encoder_learned_pos: true
decoder_learned_pos: true
max_source_positions: 2000
max_target_positions: 2000
max_tokens: 2000
dropout: 0.1
criterion: label_smoothed_cross_entropy_with_contrastive
contrastive_lambda: 1.0
temperature: 0.1
lr: 0.0003
clip_norm: 10.0
optimizer: adam
adam_eps: 1e-06
weight_decay: 0.01
warmup_updates: 10000
label_smoothing: 0.1
lr_scheduler: polynomial_decay
update_freq: 4
max_update: 500000000
total_num_update: 500000000
no_scale_embedding: true
layernorm_embedding: true
skip_invalid_size_inputs_valid_test: true
log_interval: 5
num_workers: 4
seed: 0
reset_optimizer: true
amp: true
distributed-world-size: 4
validate_interval: 10
keep_best_checkpoints: 1
keep_interval_updates: 1
save_interval_updates: 1000